data source: https://www.waterboards.ca.gov/drinking_water/certlic/drinkingwater/leadsamplinginschools.html

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('rptmonthlyposting.xls')

In [3]:
df = pd.DataFrame(data)

In [4]:
df_copy = df.copy()

In [5]:
df.shape

(20346, 16)

In [6]:
df.info

<bound method DataFrame.info of       Monday, December 3, 2018                               Unnamed: 1  \
0                        PwsID                          WaterSystemName
1                          NaN  GOLDEN STATE WATER CO - APPLE VLY SOUTH
2                          NaN  GOLDEN STATE WATER CO - APPLE VLY SOUTH
3                          NaN  GOLDEN STATE WATER CO - APPLE VLY SOUTH
4                          NaN  GOLDEN STATE WATER CO - APPLE VLY SOUTH
5                          NaN  GOLDEN STATE WATER CO - APPLE VLY SOUTH
6                    CA0110001            ALAMEDA COUNTY WATER DISTRICT
7                    CA0110001            ALAMEDA COUNTY WATER DISTRICT
8                    CA0110001            ALAMEDA COUNTY WATER DISTRICT
9                    CA0110001            ALAMEDA COUNTY WATER DISTRICT
10                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
11                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
12                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
13                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
14                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
15                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
16                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
17                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
18                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
19                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
20                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
21                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
22                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
23                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
24                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
25                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
26                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
27                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
28                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
29                   CA0110001            ALAMEDA COUNTY WATER DISTRICT
...                        ...                                      ...
20316                CA5710006                         CITY OF WOODLAND
20317                CA5710006                         CITY OF WOODLAND
20318                CA5710006                         CITY OF WOODLAND
20319                CA5710006                         CITY OF WOODLAND
20320                CA5710006                         CITY OF WOODLAND
20321                CA5710006                         CITY OF WOODLAND
20322                CA5810004                        CITY OF WHEATLAND
20323                CA5810004                        CITY OF WHEATLAND
20324                CA5810004                        CITY OF WHEATLAND
20325                CA5810004                        CITY OF WHEATLAND
20326                CA5810004                        CITY OF WHEATLAND
20327                CA5810004                        CITY OF WHEATLAND
20328                CA5810004                        CITY OF WHEATLAND
20329                CA5810004                        CITY OF WHEATLAND
20330                CA5810004                        CITY OF WHEATLAND
20331                CA5810004                        CITY OF WHEATLAND
20332                CA5810004                        CITY OF WHEATLAND
20333                CA5810004                        CITY OF WHEATLAND
20334                CA5810004                        CITY OF WHEATLAND
20335                CA5810004                        CITY OF WHEATLAND
20336                CA5810004                        CITY OF WHEATLAND
20337                CA5810004                        CITY OF WHEATLAND
20338                CA5810004                        CITY OF WHEATLAND
20339                CA5810004                        CITY OF WHEATLAND
20340                CA5810004                        CITY OF WHEATLAND
20341                CA5810004                        CITY OF WHEATLAND
20342                CA5810004                        CITY OF WHEATLAND
20343                CA5810004                        CITY OF WHEATLAND
20344                CA5810004                        CITY OF WHEATLAND
20345                CA5810004                        CITY OF WHEATLAND

              Unnamed: 2     Unnamed: 3  \
0      WaterSystemCounty         PSCODE
1         SAN BERNARDINO  3610107-AAE-A
2         SAN BERNARDINO  3610107-AAE-B
3         SAN BERNARDINO  3610107-AAE-C
4         SAN BERNARDINO  3610107-AAE-D
5         SAN BERNARDINO  3610107-AAE-E
6                ALAMEDA  0110001-AAB-A
7                ALAMEDA  0110001-AAB-B
8                ALAMEDA  0110001-AAB-C
9                ALAMEDA  0110001-AAB-C
10               ALAMEDA  0110001-AAB-C
11               ALAMEDA  0110001-AAB-D
12               ALAMEDA  0110001-AAB-E
13               ALAMEDA  0110001-AAB-E
14               ALAMEDA  0110001-AAB-E
15               ALAMEDA  0110001-AAC-A
16               ALAMEDA  0110001-AAC-B
17               ALAMEDA  0110001-AAC-C
18               ALAMEDA  0110001-AAC-D
19               ALAMEDA  0110001-AAC-E
20               ALAMEDA  0110001-AAD-A
21               ALAMEDA  0110001-AAD-B
22               ALAMEDA  0110001-AAD-C
23               ALAMEDA  0110001-AAD-D
24               ALAMEDA  0110001-AAD-E
25               ALAMEDA  0110001-AAE-A
26               ALAMEDA  0110001-AAE-B
27               ALAMEDA  0110001-AAE-C
28               ALAMEDA  0110001-AAE-D
29               ALAMEDA  0110001-AAE-E
...                  ...            ...
20316               YOLO  5710006-ABE-A
20317               YOLO  5710006-ABE-B
20318               YOLO  5710006-ABE-C
20319               YOLO  5710006-ABE-D
20320               YOLO  5710006-ABE-Z
20321               YOLO  5710006-ABF-A
20322               YUBA  5810004-AAB-A
20323               YUBA  5810004-AAB-B
20324               YUBA  5810004-AAB-D
20325               YUBA  5810004-AAB-F
20326               YUBA  5810004-AAB-H
20327               YUBA  5810004-AAC-A
20328               YUBA  5810004-AAC-D
20329               YUBA  5810004-AAC-I
20330               YUBA  5810004-AAC-M
20331               YUBA  5810004-AAC-P
20332               YUBA  5810004-AAD-B
20333               YUBA  5810004-AAD-E
20334               YUBA  5810004-AAD-F
20335               YUBA  5810004-AAD-I
20336               YUBA  5810004-AAD-L
20337               YUBA  5810004-AAE-A
20338               YUBA  5810004-AAE-F
20339               YUBA  5810004-AAE-K
20340               YUBA  5810004-AAE-O
20341               YUBA  5810004-AAE-R
20342               YUBA  5810004-AAF-A
20343               YUBA  5810004-AAF-B
20344               YUBA  5810004-AAF-C
20345               YUBA  5810004-AAF-D

                                              Unnamed: 4  \
0                                               DISTRICT
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
5                                                    NaN
6      California School for the Blind (State Special...
7      California School for the Blind (State Special...
8      California School for the Blind (State Special...
9      California School for the Blind (State Special...
10     California School for the Blind (State Special...
11     California School for the Blind (State Special...
12     California School for the Blind (State Special...
13     California School for the Blind (State Special...
14     California School for the Blind (State Special...
15     California School for the Deaf-Fremont (State ...
16     California School for the Deaf-Fremont (State ...
17     California School for the Deaf-Fremont (State ...
18     California School for the Deaf-Fremont (State ...
19     California School for the Deaf-Fremont (State ...
20                                                   NaN
21                                                   NaN
22                                                   NaN
23                                                   NaN
24                                                   NaN
25                                        Newark Unified
26                                        Newark Unified
27                                        Newark Unified
28                                        Newark Unified
29                                        Newark Unified
...                                                  ...
20316                             Woodland Joint Unified
20317                             Woodland Joint Unified
20318                             Woodland Joint Unified
20319                             Woodland Joint Unified
20320                             Woodland Joint Unified
20321                             Woodland Joint Unified
20322                               Wheatland Union High
20323                               Wheatland Union High
20324                               Wheatland Union High
20325                               Wheatland Union High
20326                               Wheatland Union High
20327                                          Wheatland
20328                                          Wheatland
20329                                          Wheatland
20330                                          Wheatland
20331                                          Wheatland
20332                    Yuba County Office of Education
20333                    Yuba County Office of Education
20334                    Yuba County Office of Education
20335                    Yuba County Office of Education
20336                    Yuba County Office of Education
20337                                          Wheatland
20338                                          Wheatland
20339                                          Wheatland
20340                                          Wheatland
20341                                          Wheatland
20342                          Wheatland School District
20343                          Wheatland School District
20344                          Wheatland School District
20345                          Wheatland School District

                                         Unnamed: 5  \
0                                        SchoolName
1                         Sycamore Rocks Elementary
2                         Sycamore Rocks Elementary
3                         Sycamore Rocks Elementary
4                         Sycamore Rocks Elementary
5                         Sycamore Rocks Elementary
6                   California School for the Blind
7                   California School for the Blind
8                   California School for the Blind
9                   California School for the Blind
10                  California School for the Blind
11                  California School for the Blind
12                  California School for the Blind
13                  California School for the Blind
14                  California School for the Blind
15           California School for the Deaf-Fremont
16           California School for the Deaf-Fremont
17           California School for the Deaf-Fremont
18           California School for the Deaf-Fremont
19           California School for the Deaf-Fremont
20                                St. Edward Parish
21                                St. Edward Parish
22                                St. Edward Parish
23                                St. Edward Parish
24                                St. Edward Parish
25     Whiteford (June) Special Education Preschool
26     Whiteford (June) Special Education Preschool
27     Whiteford (June) Special Education Preschool
28     Whiteford (June) Special Education Preschool
29     Whiteford (June) Special Education Preschool
...                                             ...
20316                      Woodland Adult Education
20317                      Woodland Adult Education
20318                      Woodland Adult Education
20319                      Woodland Adult Education
20320                      Woodland Adult Education
20321                        Woodland Community Day
20322                          Wheatland Union High
20323                          Wheatland Union High
20324                          Wheatland Union High
20325                          Wheatland Union High
20326                          Wheatland Union High
20327                                    Bear River
20328                                    Bear River
20329                                    Bear River
20330                                    Bear River
20331                                    Bear River
20332                               Virginia School
20333                               Virginia School
20334                               Virginia School
20335                               Virginia School
20336                               Virginia School
20337                          Wheatland Elementary
20338                          Wheatland Elementary
20339                          Wheatland Elementary
20340                          Wheatland Elementary
20341                          Wheatland Elementary
20342            Wheatland Child Development Center
20343            Wheatland Child Development Center
20344            Wheatland Child Development Center
20345            Wheatland Child Development Center

                                             Unnamed: 6    Unnamed: 7  \
0                                         SchoolAddress  SchoolCounty
1                                                   NaN           NaN
2                                                   NaN           NaN
3                                                   NaN           NaN
4                                                   NaN           NaN
5                                                   NaN           NaN
6               500 Walnut Avenue Fremont CA 94536-4365       Alameda
7               500 Walnut Avenue Fremont CA 94536-4365       Alameda
8               500 Walnut Avenue Fremont CA 94536-4365       Alameda
9               500 Walnut Avenue Fremont CA 94536-4365       Alameda
10              500 Walnut Avenue Fremont CA 94536-4365       Alameda
11              500 Walnut Avenue Fremont CA 94536-4365       Alameda
12              500 Walnut Avenue Fremont CA 94536-4365       Alameda
13              500 Walnut Avenue Fremont CA 94536-4365       Alameda
14              500 Walnut Avenue Fremont CA 94536-4365       Alameda
15          39350 Gallaudet Drive Fremont CA 94538-2308       Alameda
16          39350 Gallaudet Drive Fremont CA 94538-2308       Alameda
17          39350 Gallaudet Drive Fremont CA 94538-2308       Alameda
18          39350 Gallaudet Drive Fremont CA 94538-2308       Alameda
19          39350 Gallaudet Drive Fremont CA 94538-2308       Alameda
20                 5788 Thornton Avenue Newark CA 94560       Alameda
21                 5788 Thornton Avenue Newark CA 94560       Alameda
22                 5788 Thornton Avenue Newark CA 94560       Alameda
23                 5788 Thornton Avenue Newark CA 94560       Alameda
24                 5788 Thornton Avenue Newark CA 94560       Alameda
25           35725 Cedar Boulevard Newark CA 94560-1324       Alameda
26           35725 Cedar Boulevard Newark CA 94560-1324       Alameda
27           35725 Cedar Boulevard Newark CA 94560-1324       Alameda
28           35725 Cedar Boulevard Newark CA 94560-1324       Alameda
29           35725 Cedar Boulevard Newark CA 94560-1324       Alameda
...                                                 ...           ...
20316             526 Marshall Avenue Woodland CA 95695          Yolo
20317             526 Marshall Avenue Woodland CA 95695          Yolo
20318             526 Marshall Avenue Woodland CA 95695          Yolo
20319             526 Marshall Avenue Woodland CA 95695          Yolo
20320             526 Marshall Avenue Woodland CA 95695          Yolo
20321           526 Marshall Ave Woodland CA 95695-4853          Yolo
20322         1010 Wheatland Rd Wheatland CA 95692-9798          Yuba
20323         1010 Wheatland Rd Wheatland CA 95692-9798          Yuba
20324         1010 Wheatland Rd Wheatland CA 95692-9798          Yuba
20325         1010 Wheatland Rd Wheatland CA 95692-9798          Yuba
20326         1010 Wheatland Rd Wheatland CA 95692-9798          Yuba
20327  100 Wheatland Park Drive Wheatland CA 95692-9286          Yuba
20328  100 Wheatland Park Drive Wheatland CA 95692-9286          Yuba
20329  100 Wheatland Park Drive Wheatland CA 95692-9286          Yuba
20330  100 Wheatland Park Drive Wheatland CA 95692-9286          Yuba
20331  100 Wheatland Park Drive Wheatland CA 95692-9286          Yuba
20332                   801 Olive St Wheatland CA 95692          Yuba
20333                   801 Olive St Wheatland CA 95692          Yuba
20334                   801 Olive St Wheatland CA 95692          Yuba
20335                   801 Olive St Wheatland CA 95692          Yuba
20336                   801 Olive St Wheatland CA 95692          Yuba
20337         111 Hooper Street Wheatland CA 95692-8215          Yuba
20338         111 Hooper Street Wheatland CA 95692-8215          Yuba
20339         111 Hooper Street Wheatland CA 95692-8215          Yuba
20340         111 Hooper Street Wheatland CA 95692-8215          Yuba
20341         111 Hooper Street Wheatland CA 95692-8215          Yuba
20342              711 West Olive St Wheatland CA 95692          Yuba
20343              711 West Olive St Wheatland CA 95692          Yuba
20344              711 West Olive St Wheatland CA 95692          Yuba
20345              711 West Olive St Wheatland CA 95692          Yuba

                                              Unnamed: 8           Unnamed: 9  \
0                                         SchoolSiteName          SAMPLE_DATE
1                                                    NaN  2017-05-18 00:00:00
2                                                    NaN  2017-05-18 00:00:00
3                                                    NaN  2017-05-18 00:00:00
4                                                    NaN  2017-05-18 00:00:00
5                                                    NaN  2017-05-18 00:00:00
6         Center Kitchen Faucet at Sink in the Cafeteria  2017-04-11 00:00:00
7      Single water Fountain next to restrooms in Rec...  2017-04-11 00:00:00
8      Single water Fountain in restroom area in the ...  2017-04-11 00:00:00
9      Single water Fountain in restroom area in the ...  2017-04-25 00:00:00
10     Single water Fountain in restroom area in the ...  2017-12-08 00:00:00
11     Single water Fountain in Sink in Classroom # 54-8  2017-04-11 00:00:00
12      Single water Fountain in Sink in Classroom #58-4  2017-04-11 00:00:00
13      Single water Fountain in Sink in Classroom #58-4  2017-04-25 00:00:00
14      Single water Fountain in Sink in Classroom #58-4  2017-05-02 00:00:00
15     Lower Water Fountain in Early Childhood Buildi...  2017-04-25 00:00:00
16     Upper Water Fountain in front of Rm #29 in Bui...  2017-04-25 00:00:00
17     Upper Water Fountain in hallway across from MP...  2017-04-13 00:00:00
18     Upper Water Fountain near Office 207 in Buildi...  2017-04-13 00:00:00
19     Left Spigot near High School Dining Area in Bu...  2017-04-13 00:00:00
20                   Water fountain in hallway courtyard  2017-04-27 00:00:00
21                    Left sink faucet in Doolan Center   2017-04-27 00:00:00
22                   Right sink faucet in Doolan Center   2017-04-27 00:00:00

In [7]:
df.head()

,"Monday, December 3, 2018",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,PwsID,WaterSystemName,WaterSystemCounty,PSCODE,DISTRICT,SchoolName,SchoolAddress,SchoolCounty,SchoolSiteName,SAMPLE_DATE,XMOD,RESULT,RPT_UNIT,Action_Level_Exceedance?,ALE_Follow_Up_Action,ALE_Follow_Up_Status
1,NaN,GOLDEN STATE WATER CO - APPLE VLY SOUTH,SAN BERNARDINO,3610107-AAE-A,NaN,Sycamore Rocks Elementary,NaN,NaN,NaN,2017-05-18 00:00:00,<,5,UG/L,No,NaN,NaN
2,NaN,GOLDEN STATE WATER CO - APPLE VLY SOUTH,SAN BERNARDINO,3610107-AAE-B,NaN,Sycamore Rocks Elementary,NaN,NaN,NaN,2017-05-18 00:00:00,<,5,UG/L,No,NaN,NaN
3,NaN,GOLDEN STATE WATER CO - APPLE VLY SOUTH,SAN BERNARDINO,3610107-AAE-C,NaN,Sycamore Rocks Elementary,NaN,NaN,NaN,2017-05-18 00:00:00,<,5,UG/L,No,NaN,NaN
4,NaN,GOLDEN STATE WATER CO - APPLE VLY SOUTH,SAN BERNARDINO,3610107-AAE-D,NaN,Sycamore Rocks Elementary,NaN,NaN,NaN,2017-05-18 00:00:00,<,5,UG/L,No,NaN,NaN

In [8]:
cols = list(df.columns)
print (cols)

['Monday, December 3, 2018', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

In [9]:
#https://stackoverflow.com/questions/31328861/python-pandas-replacing-header-with-top-row
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header

In [10]:
# https://www.ritchieng.com/pandas-selecting-multiple-rows-and-columns/
sfusd = df[df.DISTRICT=='San Francisco Unified']

In [11]:
sfusd.head()

,PwsID,WaterSystemName,WaterSystemCounty,PSCODE,DISTRICT,SchoolName,SchoolAddress,SchoolCounty,SchoolSiteName,SAMPLE_DATE,XMOD,RESULT,RPT_UNIT,Action_Level_Exceedance?,ALE_Follow_Up_Action,ALE_Follow_Up_Status
15497,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-AAB-A,San Francisco Unified,Alamo Elementary,250 23rd Avenue San Francisco CA 94121-2009,San Francisco,Sink faucet in Rm 109 (Office),2017-04-12 00:00:00,<,5,UG/L,No,NaN,NaN
15498,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-AAB-B,San Francisco Unified,Alamo Elementary,250 23rd Avenue San Francisco CA 94121-2009,San Francisco,Sink faucet in Media Rm 110,2017-04-12 00:00:00,<,5,UG/L,No,NaN,NaN
15499,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-AAB-C,San Francisco Unified,Alamo Elementary,250 23rd Avenue San Francisco CA 94121-2009,San Francisco,Upper right drinking fountain on school yard,2017-04-12 00:00:00,<,5,UG/L,No,NaN,NaN
15500,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-AAB-D,San Francisco Unified,Alamo Elementary,250 23rd Avenue San Francisco CA 94121-2009,San Francisco,Bottle filling Station next to stairway S1-7B,2017-04-12 00:00:00,<,5,UG/L,No,NaN,NaN
15501,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-AAB-E,San Francisco Unified,Alamo Elementary,250 23rd Avenue San Francisco CA 94121-2009,San Francisco,Right kitchen faucet in Cafeteria,2017-04-12 00:00:00,<,5,UG/L,No,NaN,NaN

In [12]:
# how many fountains/etc test at or under the 5 ug/L threshold? 
#sfusd.groupby('XMOD')['RESULT'].value_counts()
sfusd.groupby(["XMOD", "RESULT"]).size()

XMOD  RESULT
<     5.00      600
=     5.15        1
      5.17        1
      5.27        1
      5.50        1
      5.61        1
      5.90        1
      6.05        1
      6.13        1
      7.28        1
      7.70        1
      8.00        1
      8.17        1
      9.10        1
      9.42        1
      9.67        1
      11.00       1
      11.70       1
      11.90       1
      12.40       1
      16.20       1
      17.60       1
      22.00       1
      33.00       1
      36.00       1
      43.00       1
      45.00       1
      49.00       1
      117.00      1
dtype: int64

In [13]:
# how many fountains/etc test above the 5 ug/L threshold?
sfusd[sfusd.RESULT > 5].SchoolName.describe()

count                28
unique               16
top       Downtown High
freq                  4
Name: SchoolName, dtype: object

In [14]:
#which schools had fountains that tested above the threshold?
sfusd[sfusd.RESULT > 5].SchoolName

15516                        Bryant Elementary
15518                        Bryant Elementary
15519                        Bryant Elementary
15564    Carver (George Washington) Elementary
15590                 Chinese Education Center
15592                 Chinese Education Center
15652              Peabody (George) Elementary
15674                     Hillcrest Elementary
15718                        Malcolm X Academy
15719                        Malcolm X Academy
15751                       Redding Elementary
15781                 Spring Valley Elementary
15784                 Spring Valley Elementary
15809                   West Portal Elementary
15811                   West Portal Elementary
15867              New School of San Francisco
15909                            Downtown High
15910                            Downtown High
15913                            Downtown High
15914                            Downtown High
15959          Bessie Carmichael Middle School
15960          Bessie Carmichael Middle School
15961          Bessie Carmichael Middle School
15978                 Marshall (Thurgood) High
15991                    Longfellow Elementary
16087             Buena Vista/ Horace Mann K-8
16374            Life Learning Academy Charter
16375            Life Learning Academy Charter
Name: SchoolName, dtype: object

In [15]:
#which schools does the above correspond to?
sfusd.groupby('RESULT')['SchoolName'].value_counts()

RESULT  SchoolName
5.00    Alamo Elementary                                    5
        Alvarado Elementary                                 5
        Aptos Middle                                        5
        Argonne Elementary                                  5
        Asawa (Ruth) SF Sch of the Arts, A Public School    5
        Balboa High                                         5
        Brown Jr. (Willie L) Middle                         5
        Burton (Phillip and Sala) Academic High             5
        Chavez (Cesar) Elementary                           5
        Chin (John Yehall) Elementary                       5
        Chinese Immersion School at DeAvila                 5
        City Arts and Tech High                             5
        Clarendon Alternative Elementary                    5
        Cleveland Elementary                                5
        Cobb (William L.) Elementary                        5
        Cooper (Sarah B) Children Center                    5
        Creative Arts Charter                               5
        Denman (James) Middle                               5
        Drew (Charles) College Preparatory Academy          5
        Edison Charter Academy                              5
        Everett Middle                                      5
        Fairmount Elementary                                5
        Feinstein (Dianne) Elementary                       5
        Francisco Middle                                    5
        Galileo High                                        5
        Gateway High                                        5
        Gateway Middle                                      5
        Giannini (A.P.) Middle                              5
        Glen Park Elementary                                5
        Grattan Elementary                                  5
                                                           ..
        Bryant Elementary                                   2
        Yick Wo Elementary                                  1
5.15    Chinese Education Center                            1
5.17    Carver (George Washington) Elementary               1
5.27    Bryant Elementary                                   1
5.50    Buena Vista/ Horace Mann K-8                        1
5.61    Bryant Elementary                                   1
5.90    Longfellow Elementary                               1
6.05    Hillcrest Elementary                                1
6.13    Spring Valley Elementary                            1
7.28    Spring Valley Elementary                            1
7.70    Marshall (Thurgood) High                            1
8.00    Bessie Carmichael Middle School                     1
8.17    Peabody (George) Elementary                         1
9.10    Bessie Carmichael Middle School                     1
9.42    West Portal Elementary                              1
9.67    Chinese Education Center                            1
11.00   Bessie Carmichael Middle School                     1
11.70   Bryant Elementary                                   1
11.90   Redding Elementary                                  1
12.40   New School of San Francisco                         1
16.20   Malcolm X Academy                                   1
17.60   Malcolm X Academy                                   1
22.00   Life Learning Academy Charter                       1
33.00   Downtown High                                       1
36.00   Downtown High                                       1
43.00   Downtown High                                       1
45.00   Life Learning Academy Charter                       1
49.00   Downtown High                                       1
117.00  West Portal Elementary                              1
Name: SchoolName, Length: 154, dtype: int64

In [16]:
#get more specifics on each of the counts for schools with results higher than 5
sfusd.groupby('SchoolName')['RESULT'].value_counts()

SchoolName                                         RESULT
Alamo Elementary                                   5.00      5
Alvarado Elementary                                5.00      5
Aptos Middle                                       5.00      5
Argonne Elementary                                 5.00      5
Asawa (Ruth) SF Sch of the Arts, A Public School   5.00      5
Balboa High                                        5.00      5
Bessie Carmichael Middle School                    5.00      2
                                                   8.00      1
                                                   9.10      1
                                                   11.00     1
Brown Jr. (Willie L) Middle                        5.00      5
Bryant Elementary                                  5.00      2
                                                   5.27      1
                                                   5.61      1
                                                   11.70     1
Buena Vista/ Horace Mann K-8                       5.00      4
                                                   5.50      1
Burton (Phillip and Sala) Academic High            5.00      5
Carmichael (Bessie)/FEC                            5.00      3
Carver (George Washington) Elementary              5.00      4
                                                   5.17      1
Chavez (Cesar) Elementary                          5.00      5
Chin (John Yehall) Elementary                      5.00      5
Chinese Education Center                           5.00      3
                                                   5.15      1
                                                   9.67      1
Chinese Immersion School at DeAvila                5.00      5
City Arts and Tech High                            5.00      5
Clarendon Alternative Elementary                   5.00      5
Cleveland Elementary                               5.00      5
                                                            ..
Sanchez Elementary                                 5.00      5
Serra (Junipero) Elementary                        5.00      5
Serra, Junipero, (Annex) Early Education School    5.00      5
Sheridan Elementary                                5.00      5
Sherman Elementary                                 5.00      5
Sloat (Commodore) Elementary                       5.00      5
Spring Valley Elementary                           5.00      3
                                                   6.13      1
                                                   7.28      1
Stevenson (Robert Louis) Elementary                5.00      5
Stockton (Commodore) Children Center               5.00      5
Sunnyside Elementary                               5.00      5
Sunset Elementary                                  5.00      5
Sutro Elementary                                   5.00      5
Taylor (Edward R.) Elementary                      5.00      5
Tenderloin Community                               5.00      5
The Academy - San Francisco                        5.00      5
Ulloa Elementary                                   5.00      5
Visitacion Valley Elementary                       5.00      5
Visitacion Valley Middle                           5.00      5
Wallenberg (Raoul) Traditional High                5.00      5
Washington (George) High                           5.00      5
Webster (Daniel) Elementary                        5.00      5
Weill (Raphael) Children Center                    5.00      5
Wells (Ida B.) High                                5.00      5
West Portal Elementary                             5.00      5
                                                   9.42      1
                                                   117.00    1
Yick Wo Elementary                                 5.00      1
Yu (Alice Fong) Elementary                         5.00      5
Name: RESULT, Length: 154, dtype: int64

In [17]:
# https://stackoverflow.com/questions/24988873/python-sort-descending-dataframe-with-pandas
# https://medium.com/@msalmon00/helpful-python-code-snippets-for-data-exploration-in-pandas-b7c5aed5ecb9
sfusd_sort = sfusd.sort_values(['RESULT','XMOD','SchoolName'], ascending=[0,1,1]) 
print(sfusd_sort.head())

0          PwsID                   WaterSystemName WaterSystemCounty  \
15809  CA3810011  SFPUC CITY DISTRIBUTION DIVISION     SAN FRANCISCO
15913  CA3810011  SFPUC CITY DISTRIBUTION DIVISION     SAN FRANCISCO
16375  CA3810702                   TREASURE ISLAND     SAN FRANCISCO
15909  CA3810011  SFPUC CITY DISTRIBUTION DIVISION     SAN FRANCISCO
15910  CA3810011  SFPUC CITY DISTRIBUTION DIVISION     SAN FRANCISCO

0             PSCODE               DISTRICT                     SchoolName  \
15809  3810011-AGD-E  San Francisco Unified         West Portal Elementary
15913  3810011-AIH-D  San Francisco Unified                  Downtown High
16375  3810702-AAB-E  San Francisco Unified  Life Learning Academy Charter
15909  3810011-AIH-A  San Francisco Unified                  Downtown High
15910  3810011-AIH-A  San Francisco Unified                  Downtown High

0                                          SchoolAddress   SchoolCounty  \
15809            5 Lenox Way San Francisco CA 94127-1111  San Francisco
15913     693 Vermont Street San Francisco CA 94107-2635  San Francisco
16375  651 Eighth Street Building 229 Treasure Island...  San Francisco
15909     693 Vermont Street San Francisco CA 94107-2635  San Francisco
15910     693 Vermont Street San Francisco CA 94107-2635  San Francisco

0                                         SchoolSiteName          SAMPLE_DATE  \
15809  Sink faucet farthest to left on wall with urin...  2017-10-18 00:00:00
15913  Upper drinking fountain across from Room 115 o...  2017-12-05 00:00:00
16375  Cold water faucet in Principal's bathroom behi...  2018-04-13 00:00:00
15909  Lower drinking fountain of fountain-water bott...  2017-12-05 00:00:00
15910  Lower drinking fountain of fountain-water bott...  2017-12-12 00:00:00

0     XMOD RESULT RPT_UNIT Action_Level_Exceedance?  \
15809    =    117     UG/L                      Yes
15913    =     49     UG/L                      Yes
16375    =     45     UG/L                      Yes
15909    =     43     UG/L                      Yes
15910    =     36     UG/L                      Yes

0                    ALE_Follow_Up_Action ALE_Follow_Up_Status
15809        Fixture removed from service             Complete
15913        Fixture removed from service             Complete
16375  Contacted system, response pending              Pending
15909        Fixture removed from service             Complete
15910        Fixture removed from service             Complete

In [18]:
# look for specific school results
# https://stackoverflow.com/questions/26640129/search-for-string-in-all-pandas-dataframe-columns-and-filter
CIS_mask = np.column_stack([sfusd[col].str.contains("Chinese Immersion School at DeAvila", na=False) for col in sfusd])
sfusd.loc[CIS_mask.any(axis=1)]

,PwsID,WaterSystemName,WaterSystemCounty,PSCODE,DISTRICT,SchoolName,SchoolAddress,SchoolCounty,SchoolSiteName,SAMPLE_DATE,XMOD,RESULT,RPT_UNIT,Action_Level_Exceedance?,ALE_Follow_Up_Action,ALE_Follow_Up_Status
15595,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-ACB-A,San Francisco Unified,Chinese Immersion School at DeAvila,1250 Waller Street San Francisco CA 94117-2919,San Francisco,Sink faucet inside Room 208 (Teacher's lounge)...,2017-09-27 00:00:00,<,5,UG/L,No,NaN,NaN
15596,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-ACB-B,San Francisco Unified,Chinese Immersion School at DeAvila,1250 Waller Street San Francisco CA 94117-2919,San Francisco,Food Prep Sink Faucet (left one when facing fa...,2017-09-27 00:00:00,<,5,UG/L,No,NaN,NaN
15597,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-ACB-C,San Francisco Unified,Chinese Immersion School at DeAvila,1250 Waller Street San Francisco CA 94117-2919,San Francisco,Lower drinking fountain in middle courtyard #6...,2017-09-27 00:00:00,<,5,UG/L,No,NaN,NaN
15598,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-ACB-D,San Francisco Unified,Chinese Immersion School at DeAvila,1250 Waller Street San Francisco CA 94117-2919,San Francisco,Lower drinking fountain in courtyard #3 near b...,2017-09-27 00:00:00,<,5,UG/L,No,NaN,NaN
15599,CA3810011,SFPUC CITY DISTRIBUTION DIVISION,SAN FRANCISCO,3810011-ACB-E,San Francisco Unified,Chinese Immersion School at DeAvila,1250 Waller Street San Francisco CA 94117-2919,San Francisco,Lower drinking fountain on basketball court cl...,2017-09-27 00:00:00,<,5,UG/L,No,NaN,NaN

TO DO Testing area
sfusd = df['DISTRICT'] == "San Francisco Unified"
# Create variables with TRUE for lead levels
leadlow = df['RESULT'] < 5
leadlevel = df['RESULT'] == 5
leadhigh = df['RESULT'] > 5

# Select all cases where...
df[sfusd & leadhigh]

sfusd[sfusd.RESULT > 5].SchoolName

https://towardsdatascience.com/seven-clean-steps-to-reshape-your-data-with-pandas-or-how-i-use-python-where-excel-fails-62061f86ef9c